// react/src/ChatMessages.js
import { useEffect } from 'react';

function ChatMessages(props) {
  useEffect(() => {
    const messagesComponent = document.querySelector('chat-messages');
    // set from and to
    messagesComponent.from = props.from;
    messagesComponent.to = props.to;
  });

  return <chat-messages />;
}

export default ChatMessages;

// svelte/src/ChatMessages.svelte
<script>
	import { onMount } from 'svelte';

	export let from;
    export let to;

	onMount(() => {
	  const messagesComponent = document.querySelector('chat-messages');
      // set from and to
      messagesComponent.from = from;
      messagesComponent.to = to;
	});
</script>

<main>
	<chat-messages></chat-messages>
</main>

<style>
</style>
