// svelte/src/App.svelte
<script>
  	import ChatMessages from './ChatMessages.svelte'

	export let CURRENT_USER
	export let CURRENT_GROUPS

	// apply dark theme
	const prefersDark = window.matchMedia('(prefers-color-scheme: dark)');
	uiToggleDark(prefersDark.matches);
	prefersDark.addListener((mediaQuery) => uiToggleDark(mediaQuery.matches));
	function uiToggleDark(shouldAdd) {
		document.body.classList.toggle('dark', shouldAdd);
	}
</script>

<main>
	<h2 class="outer">Hello {CURRENT_USER.name}!</h2>
	<ChatMessages bind:from={CURRENT_USER} bind:to={CURRENT_GROUPS[0]}></ChatMessages>
</main>



<svelte:head>
	<script type="text/javascript" src="https://static.chatness.app/js/elements.js"></script>
	<style>
		html, body {
			overflow-y: auto !important;
		}
		h2.outer {
			text-align: center;
			margin-top: 50px;
			display: block;
		}
		@media (prefers-color-scheme: dark) {
			h2.outer {
				color: #fff;
			}
		}
	</style>
</svelte:head>

// vue/src/App.vue
<template>
  <div>
    <h2 class="outer">Hello {{ from.name }}!</h2>
    <AppChatMessages :from="from" :to="to" />
  </div>
</template>

<script>
import AppChatMessages from './components/AppChatMessages.vue';

// apply dark theme
const prefersDark = window.matchMedia('(prefers-color-scheme: dark)');
uiToggleDark(prefersDark.matches);
prefersDark.addListener((mediaQuery) => uiToggleDark(mediaQuery.matches));
function uiToggleDark(shouldAdd) {
  document.body.classList.toggle('dark', shouldAdd);
}

export default {
  name: 'App',
  data() {
    return {
      from: {
        name: 'John Doe',
        objectId: '5EOJTH9nUzM526vKPSVrHzp2zFP2',
        email: 'john@doe.com',
      },
      to: {
        objectId: '4e1cda1f-4adf-2fce-f303-83f497ce25c9',
        name: 'Developers',
      },
    };
  },
  components: {
    AppChatMessages,
  },
};
</script>

<style>
body,
html {
  overflow-y: auto !important;
}
h2.outer {
  text-align: center;
  margin-top: 50px;
  display: block;
}
@media (prefers-color-scheme: dark) {
  h2.outer {
    color: #fff;
  }
}
</style>
